language: node_js
node_js:
- 6
notifications:
  email: false
addons:
  sauce_connect:
    username: PanJs
env:
  global:
  - secure: kkcizD3Hytnvd/lDRoumsiIBa7A8bjw9O17ROHGqSZ8pzR6MslbT0XD1B05zNr2Ov10FCqaXzcd4R9yQHr6Mc//czuKn65hVL7agXbrYAnwHy6rDRge76kVeuSvrgBRzSTvj0QKdh53N9eZCb7Kemy367M/68J6tm5LV8aNA1tIH65tu/bz+jEbXBVq1k8HTdnIGsQgNrwI7HZaW6z8qECEfivv+LBTyRe/Gf5iEs0n7UuftPDnel2T7DGjJeNsjMARt1XxaOiVFuBVcNs/DoIngBUc+px1p6rqhaSLPdfk/SdXw9NVnVT2JzZgLMwzlGzneQnj/laD6UU/pwe2l7Iy6uqiMnfc5rgkYHC3vm284LhHz8B64215Qq/mpNKt6vMF+gpm8EVWG58TeSWZvbdRAynnm8PFQX3A6l7zwoELgDS9cdeOAdzXZ26vA3fUm2tSltztXdyU80yAjKmPc4m6+fVLYyUDgM6hlBrMxC4bkmfhJ2yMnc60I8RhkasAfZrgrpdl00hP2SzEJpUEIiUIzZHmvFXoemQcnxId7hBIfghZPytcZLjzNoMOj//37T/G7wKou5oBeSM2iL2HRozTimWvSykerppRNQDKvJGL9xHzAU22kuqvLWwCLZdpBDAhwal1ARNjSh6B/wEE1tf04KGY/pkKw55MjayYKCes=
