language: node_js
node_js:
- 6
notifications:
  email: false
addons:
  sauce_connect:
    username: PanJs
env:
  global:
    secure: Z7ekWwQjxDYF/ZhlUB377ISfFodL2w3QggJI4ngXk0wJRQSsMi2yTiCfREqUhlZBpT9gFUPSTle7ata8YO/uwwkFc/37L+pE6oWCYPWgSTWKy1rubHNPkcoqrXXqr/mJOPurVE4SKeasP3L+/7FuayBxPjK7H3fk8361s/ErEYdSOx0yU2yPfiJIcvFL5D/Zy3EJYQxpYCS6j7/FF++mbTfJAQN84yFTrO+CJWGK5fxRwwD1c/lPu3KO0RAFtnQ6K3fU5m0181qL0pKaNJ9lKzOdHN1RcbPYAENiYAPt073h3gDXSVZxIaMVLyD42zd4hnfh1ir8t2GIP9gFS1ZFz9SFC5A+vWic3W/I2Daz811go6Fx/hFvIx73OTqdBBr2xC0Y3WdmvjTEAT9rBhGPta6U9JNRh+g1EyP+zDBJmXJWvZR+I45oNoCJqhbynFyrRHP9VgADKemlOjHkY7dXXFa3DyY0P9XWDz/UOHGTNF4WQVP0To0pJIcu2NOC4yo+kZbSRcf/vrdK2c7FhxgmwESmT6EPd1oVv/vd18+AMnd1zdnMaJJ2GEIxZx1QJOYEpP8waNZ7ED7mme0f8V0RFcDE3sU2IYI2PiOYdbXURr1/wWYm9rXqcEkLCaT7YUBvsFaAb7iKia5/Yk8ZplZfijGtZ8fiyvPDTrb85iEa7SE=
